/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.udesc.bakeryhub.view;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author crist
 */
public class InicialView extends javax.swing.JFrame {

    public InicialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        miCadastroCliente = new javax.swing.JMenuItem();
        miConsultaCliente = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miCadastroFuncionario = new javax.swing.JMenuItem();
        miConsultaFuncionario = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenu();
        miCadastroProduto = new javax.swing.JMenuItem();
        miConsultaProduto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miCadastroDespesa = new javax.swing.JMenuItem();
        miConsultaDespesa = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miCadastroVenda = new javax.swing.JMenuItem();
        miConsultaVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bakery Hub");
        setIconImages(null);

        jMenu2.setText("Clientes");

        miCadastroCliente.setText("Cadastro");
        miCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroClienteActionPerformed(evt);
            }
        });
        jMenu2.add(miCadastroCliente);

        miConsultaCliente.setText("Consulta");
        jMenu2.add(miConsultaCliente);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Funcionários");

        miCadastroFuncionario.setText("Cadastro");
        jMenu1.add(miCadastroFuncionario);

        miConsultaFuncionario.setText("Consulta");
        jMenu1.add(miConsultaFuncionario);

        jMenuBar1.add(jMenu1);

        Produtos.setText("Produtos");

        miCadastroProduto.setText("Cadastro");
        Produtos.add(miCadastroProduto);

        miConsultaProduto.setText("Consulta");
        Produtos.add(miConsultaProduto);

        jMenuBar1.add(Produtos);

        jMenu3.setText("Despesas");

        miCadastroDespesa.setText("Cadastro");
        jMenu3.add(miCadastroDespesa);

        miConsultaDespesa.setText("Consulta");
        jMenu3.add(miConsultaDespesa);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Vendas");

        miCadastroVenda.setText("Cadastro");
        jMenu4.add(miCadastroVenda);

        miConsultaVenda.setText("Consulta");
        jMenu4.add(miConsultaVenda);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(627, Short.MAX_VALUE)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadastroClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Produtos;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem miCadastroCliente;
    public javax.swing.JMenuItem miCadastroDespesa;
    public javax.swing.JMenuItem miCadastroFuncionario;
    public javax.swing.JMenuItem miCadastroProduto;
    public javax.swing.JMenuItem miCadastroVenda;
    public javax.swing.JMenuItem miConsultaCliente;
    public javax.swing.JMenuItem miConsultaDespesa;
    public javax.swing.JMenuItem miConsultaFuncionario;
    public javax.swing.JMenuItem miConsultaProduto;
    public javax.swing.JMenuItem miConsultaVenda;
    // End of variables declaration//GEN-END:variables
}
